# Versão do template - não alterar
AWSTemplateFormatVersion: "2010-09-09"
# Descrição que será utilizada na stack
Description: Criacao de bucket S3 e disparo de mensagem SNS
# Parâmetros
Parameters:
  SufixoBucket:
    Type: String
    Default: prova-dataops
# Recursos que serão provisionados
Resources:
  # Provisionar um Bucket S3 privado
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub deploy-${SufixoBucket}-${AWS::AccountId}-${AWS::Region}
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref "SnsTopic"
            Event: "s3:ObjectCreated:*"
          - Topic: !Ref "SnsTopic"
            Event: "s3:ObjectRemoved:*"

      # Provisionar Tópico SNS
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Topico-Evento-Deploy-S3
   #Provisionar assinatura do tópico
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: julia.araujo@aluno.faculdadeimpacta.com.br
      TopicArn: !Ref "SnsTopic"
  # Provisionar política do tópico - receber publicacao do S3
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref "SnsTopic"
      PolicyDocument:
        Id: TopicPolicyNotificationS3
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref "SnsTopic"
            Condition:
              ArnLike:
                aws:SourceArn: 
                  !Join
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref "S3Bucket"
#Saídas mostradas no CloudFormation
Outputs:
  ArnBucket:
    Description: Nome do bucket
    Value:
     !Join
      - ""
      - - "arn:aws:s3:::"
        - !Ref "S3Bucket"
  NomeBucket:
    Description: Nome do bucket
    Value: Ref 'S3Bucket'
